[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.commerce.quotes"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["commerce", "quotes", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.quotes"

[build-options]
observabilityIncluded = true
